# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Esteves
paginate:       5
baseurl:        ""
url:            "https://esteveste.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Esteves
  # url:          
  # email:        chesterhow@gmail.com

# Custom vars
version:        3.4.1
github:
  # repo:         

# Gems
gems:
  - jekyll-paginate
